### ISSUE TITLE
Aaron's CARD gene fixes

### ISSUE THREAD

**Issue by emilydc** [czbiohub/flash#32]
Aaron identified a few genes that had changed in the latest release of CARD that we wanted to follow up on. I looked into each of them and in each case concluded that we should go with CARD's new version of the gene. My reasoning is as follows:

abcA: This is a fungal gene, and they seem to have replaced the DNA sequence with a cDNA sequence that has a few small introns missing. So let's use the NEW sequence (gb|XM_748018.1|+|0-4359|ARO:3003942|abcA)

CpxR: I don't know why they removed it, but there are a lot of other cpxR sequences in here so I think we can just leave it out.

dfrE: It looks like the old sequence was an error (it was actually a totally different gene). So let's use the NEW sequence (gb|AIIS01000002.1|-|233812-234307|ARO:3002875|dfrE)

mexR: They removed an "A" from the beginning of the sequence that was probably not supposed to be there in the first place (it was before the start codon). So let's use the NEW sequence (gb|NC_002516.2|-|471305-471749|ARO:3000506|mexR)

Emily

**Comment by neevor** [comment]
This had been committed.
