### ISSUE TITLE
U instead of T

### ISSUE THREAD

**Issue by emilydc** [czbiohub/flash#33]
Really minor but the CDC's RSV samples are coded as RNA not DNA, meaning Us instead of Ts. Would be great if FLASHit could automatically replace Us with Ts for easier usage.

**Comment by batson** [comment]
This should be a preprocessing step that can be run on a fasta someone gives us.

They will want to be able to, eg, cut their genes with a library too, so there should just be a script that can do this.

Resolved: #36
