### ISSUE TITLE
Flash and small fasta file (viruses)

### ISSUE THREAD

**Issue by AmyNjaaye** [czbiohub/flash#44]
I tried to define guide RNA for viruses. It works for viruses with a large genome such as CMV but it did not work with viruses (DNA or RNA) with a genome size < 40 Kb (Adenovirus, coronavirus, picornavirus). Is there a way to overcome this issue ?
You can find below the error returned by the pipeline at its first steps (make library function). you can also find attached the fasta file (renamed .txt because of format accepted by github)
[TOTALPBV60.txt](https://github.com/czbiohub/flash/files/2992909/TOTALPBV60.txt)

Thank you.

The command line used: 

`make library TARGETS=to_test/TOTALPBV60.fasta OUTPUT=to_test/TOTALPBV60.library.txt`

The error returned: 

```
Traceback (most recent call last):
  File "filter_offtarget.py", line 77, in <module>
    retcode = main()
  File "filter_offtarget.py", line 71, in main
    output(build.off_targets_path, results)
  File "filter_offtarget.py", line 54, in output
    assert len(words) == 2
AssertionError
Traceback (most recent call last):
  File "build_indices.py", line 38, in <module>
    retcode = main()
  File "build_indices.py", line 15, in main
    subprocess.check_call("python filter_offtarget.py".split())
  File "/home/labo/miniconda3/envs/flash/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'filter_offtarget.py']' returned non-zero exit status 1
make[1]: *** [build_indices] Erreur 1
make[1]: quittant le répertoire « /home/labo/flash »
make: *** [library] Erreur 2
```

**Comment by neevor** [comment]
Hi @AmyNjaaye sorry we missed this issue and took so long to get back to you. I'll take a look today and follow up with any questions or findings.

**Comment by neevor** [comment]
@AmyNjaaye I haven't been able to reproduce the error, but created a branch that might help a bit by giving me the results of the value failing the assertion. Would you be able to checkout the branch `neevor/debug_issue_44` and run:

```
make library TARGETS=to_test/TOTALPBV60.fasta OUTPUT=to_test/TOTALPBV60.library.txt &> output.log
```

and send me the output.log file after?
